name: "melos_cli"
description: ""
version: "0.0.1"
executables:
  melos:
dependencies:
  args: "1.6.0"
  pool: "1.4.0"
  collection: ^1.14.12
  string_scanner: ^1.0.5
  cli_util: ^0.1.4
  glob: "1.2.0"
  yaml: "2.2.1"
  yamlicious: "0.1.0"
  pub_semver: "1.4.4"
dev_dependencies:
  pedantic: ^1.9.0
environment:
  sdk: ">=2.2.2 <3.0.0"
