description: "Sidecar Project for FlutterFire for easier plugin development."
homepage: "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core_web"
name: "flutterfire_monorepo"
version: "0.0.1"
dependencies: 
  yaml: "2.2.1"
  yamlicious: "0.1.0"
  cloud_firestore: 
    path: "../flutterfire/packages/cloud_firestore/cloud_firestore"
  cloud_firestore_platform_interface: 
    path: "../flutterfire/packages/cloud_firestore/cloud_firestore_platform_interface"
  cloud_firestore_web: 
    path: "../flutterfire/packages/cloud_firestore/cloud_firestore_web"
  cloud_functions: 
    path: "../flutterfire/packages/cloud_functions/cloud_functions"
  cloud_functions_platform_interface: 
    path: "../flutterfire/packages/cloud_functions/cloud_functions_platform_interface"
  cloud_functions_web: 
    path: "../flutterfire/packages/cloud_functions/cloud_functions_web"
  firebase_admob: 
    path: "../flutterfire/packages/firebase_admob"
  firebase_analytics: 
    path: "../flutterfire/packages/firebase_analytics/firebase_analytics"
  firebase_analytics_platform_interface: 
    path: "../flutterfire/packages/firebase_analytics/firebase_analytics_platform_interface"
  firebase_auth: 
    path: "../flutterfire/packages/firebase_auth/firebase_auth"
  firebase_auth_platform_interface: 
    path: "../flutterfire/packages/firebase_auth/firebase_auth_platform_interface"
  firebase_auth_web: 
    path: "../flutterfire/packages/firebase_auth/firebase_auth_web"
  firebase_core: 
    path: "../flutterfire/packages/firebase_core/firebase_core"
  firebase_core_platform_interface: 
    path: "../flutterfire/packages/firebase_core/firebase_core_platform_interface"
  firebase_core_web: 
    path: "../flutterfire/packages/firebase_core/firebase_core_web"
  firebase_crashlytics: 
    path: "../flutterfire/packages/firebase_crashlytics"
  firebase_database: 
    path: "../flutterfire/packages/firebase_database"
  firebase_dynamic_links: 
    path: "../flutterfire/packages/firebase_dynamic_links"
  firebase_in_app_messaging: 
    path: "../flutterfire/packages/firebase_in_app_messaging"
  firebase_messaging: 
    path: "../flutterfire/packages/firebase_messaging"
  firebase_ml_vision: 
    path: "../flutterfire/packages/firebase_ml_vision"
  firebase_performance: 
    path: "../flutterfire/packages/firebase_performance"
  firebase_remote_config: 
    path: "../flutterfire/packages/firebase_remote_config"
  firebase_storage: 
    path: "../flutterfire/packages/firebase_storage"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  cloud_firestore: 
    path: "../flutterfire/packages/cloud_firestore/cloud_firestore"
  cloud_firestore_platform_interface: 
    path: "../flutterfire/packages/cloud_firestore/cloud_firestore_platform_interface"
  cloud_firestore_web: 
    path: "../flutterfire/packages/cloud_firestore/cloud_firestore_web"
  cloud_functions: 
    path: "../flutterfire/packages/cloud_functions/cloud_functions"
  cloud_functions_platform_interface: 
    path: "../flutterfire/packages/cloud_functions/cloud_functions_platform_interface"
  cloud_functions_web: 
    path: "../flutterfire/packages/cloud_functions/cloud_functions_web"
  firebase_admob: 
    path: "../flutterfire/packages/firebase_admob"
  firebase_analytics: 
    path: "../flutterfire/packages/firebase_analytics/firebase_analytics"
  firebase_analytics_platform_interface: 
    path: "../flutterfire/packages/firebase_analytics/firebase_analytics_platform_interface"
  firebase_auth: 
    path: "../flutterfire/packages/firebase_auth/firebase_auth"
  firebase_auth_platform_interface: 
    path: "../flutterfire/packages/firebase_auth/firebase_auth_platform_interface"
  firebase_auth_web: 
    path: "../flutterfire/packages/firebase_auth/firebase_auth_web"
  firebase_core: 
    path: "../flutterfire/packages/firebase_core/firebase_core"
  firebase_core_platform_interface: 
    path: "../flutterfire/packages/firebase_core/firebase_core_platform_interface"
  firebase_core_web: 
    path: "../flutterfire/packages/firebase_core/firebase_core_web"
  firebase_crashlytics: 
    path: "../flutterfire/packages/firebase_crashlytics"
  firebase_database: 
    path: "../flutterfire/packages/firebase_database"
  firebase_dynamic_links: 
    path: "../flutterfire/packages/firebase_dynamic_links"
  firebase_in_app_messaging: 
    path: "../flutterfire/packages/firebase_in_app_messaging"
  firebase_messaging: 
    path: "../flutterfire/packages/firebase_messaging"
  firebase_ml_vision: 
    path: "../flutterfire/packages/firebase_ml_vision"
  firebase_performance: 
    path: "../flutterfire/packages/firebase_performance"
  firebase_remote_config: 
    path: "../flutterfire/packages/firebase_remote_config"
  firebase_storage: 
    path: "../flutterfire/packages/firebase_storage"
environment: 
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
