name: "melos_cli"
description: ""
version: "0.0.1"
executables:
  melos:
dependencies:
  args: "1.6.0"
  cli_util: ^0.1.3+2
  yaml: "2.2.1"
  yamlicious: "0.1.0"
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
