name: "conventional_commit"
description: "Parse a git commit message using the Conventional Commits specification."
version: "0.3.0"
homepage: "https://github.com/invertase/melos/tree/master/packages/conventional_commit"
dev_dependencies:
  test: any
environment:
  sdk: ">=2.2.2 <3.0.0"
